import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'https://apis.falcon-head.org/graphql',
  documents: ['**/*.graphql', '!generated/**/*'], // exclude generated output
  generates: {
    "./types/__generated__/graphql.ts": {
      plugins: ["typescript-operations"],
      config: {
        // Generates the enum and input types used in operation variables.
        // The files generated from the config below import these types into near-operation files.
        generateOperationTypes: false,
      },
    },
    "./": {
      preset: "near-operation-file",
      plugins: ["typescript-operations", "typed-document-node"],
      // Note: these config options moved from the other generated file config
      config: {
        // This is the file generated by the `typescript-operations` plugin above,
        // relative to the current working directory.
        importSchemaTypesFrom: "./types/__generated__/graphql.ts",
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
      },
    },
  }
};

export default config;